# Generated by Django 4.2.3 on 2023-07-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='currentFloor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elevator',
            name='nextFloor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
