# Generated by Django 4.2.3 on 2023-07-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0002_elevator_currentfloor_elevator_nextfloor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevator',
            name='nextFloor',
        ),
        migrations.AddField(
            model_name='elevator',
            name='isUnderMaintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elevator',
            name='isWorking',
            field=models.BooleanField(default=True),
        ),
    ]
